/* tslint:disable */
/* eslint-disable */
/**
 * StellerSL API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface BadgeItem {
    'description': string;
    'icon_slug': string;
    'id': string;
    'name': string;
}
export interface BadgeListOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'items': Array<BadgeItem> | null;
}
export interface BulkTaskCreateInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'tasks': Array<BulkTaskCreateItem> | null;
}
export interface BulkTaskCreateItem {
    'description': string;
    'project_id': string;
    'title': string;
}
export interface BulkTaskDeleteInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'ids': Array<string> | null;
}
export interface BulkTaskUpdateInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'ids': Array<string> | null;
    'status': BulkTaskUpdateInputBodyStatusEnum;
}

export const BulkTaskUpdateInputBodyStatusEnum = {
    Todo: 'todo',
    Doing: 'doing',
    Done: 'done'
} as const;

export type BulkTaskUpdateInputBodyStatusEnum = typeof BulkTaskUpdateInputBodyStatusEnum[keyof typeof BulkTaskUpdateInputBodyStatusEnum];

export interface DashboardOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'completed_tasks': number;
    'daily_activity': Array<Item> | null;
    'pending_tasks': number;
    'total_tasks': number;
}
export interface ErrorDetail {
    /**
     * Where the error occurred, e.g. \'body.items[3].tags\' or \'path.thing-id\'
     */
    'location'?: string;
    /**
     * Error message text
     */
    'message'?: string;
    'value'?: any;
}
export interface ErrorModel {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    'detail'?: string;
    /**
     * Optional list of individual error details
     */
    'errors'?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    'instance'?: string;
    /**
     * HTTP status code
     */
    'status'?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    'title'?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    'type'?: string;
}
export interface GrowthOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'character_type': string;
    'exp': number;
    'level': number;
}
export interface Item {
    'completed': number;
    'created': number;
    'date': string;
}
export interface LoginInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'email': string;
    'password': string;
}
export interface LoginOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'token': string;
    'user': UserStruct;
}
export interface ProjectInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'description': string;
    'name': string;
}
export interface ProjectItem {
    'description': string;
    'id': string;
    'name': string;
}
export interface ProjectListOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'items': Array<ProjectItem> | null;
}
export interface ProjectOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'created_at': string;
    'description': string;
    'id': string;
    'name': string;
    'updated_at': string;
}
export interface RegisterInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'email': string;
    'name': string;
    'password': string;
    'tenant_id': string;
}
export interface TaskInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'assigned_to'?: string;
    'description': string;
    'due_date'?: string;
    'priority': number;
    'project_id'?: string;
    'status': TaskInputBodyStatusEnum;
    'title': string;
}

export const TaskInputBodyStatusEnum = {
    Todo: 'todo',
    Doing: 'doing',
    Done: 'done'
} as const;

export type TaskInputBodyStatusEnum = typeof TaskInputBodyStatusEnum[keyof typeof TaskInputBodyStatusEnum];

export interface TaskItem {
    'id': string;
    'priority': number;
    'project_id': string;
    'status': string;
    'title': string;
}
export interface TaskListOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'items': Array<TaskItem> | null;
}
export interface TaskOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'created_at': string;
    'description': string;
    'due_date': string;
    'id': string;
    'priority': number;
    'project_id': string;
    'status': string;
    'title': string;
    'updated_at': string;
}
export interface TaskStatusUpdateInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'status': TaskStatusUpdateInputBodyStatusEnum;
}

export const TaskStatusUpdateInputBodyStatusEnum = {
    Todo: 'todo',
    Doing: 'doing',
    Done: 'done'
} as const;

export type TaskStatusUpdateInputBodyStatusEnum = typeof TaskStatusUpdateInputBodyStatusEnum[keyof typeof TaskStatusUpdateInputBodyStatusEnum];

export interface TeamInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'name': string;
}
export interface TeamItem {
    'id': string;
    'name': string;
}
export interface TeamListOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'items': Array<TeamItem> | null;
}
export interface TeamMemberInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'role': TeamMemberInputBodyRoleEnum;
    'user_id': string;
}

export const TeamMemberInputBodyRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member'
} as const;

export type TeamMemberInputBodyRoleEnum = typeof TeamMemberInputBodyRoleEnum[keyof typeof TeamMemberInputBodyRoleEnum];

export interface UserStruct {
    'email': string;
    'id': string;
    'name': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add Team Member
         * @param {string} id 
         * @param {TeamMemberInputBody} teamMemberInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTeamMember: async (id: string, teamMemberInputBody: TeamMemberInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addTeamMember', 'id', id)
            // verify required parameter 'teamMemberInputBody' is not null or undefined
            assertParamExists('addTeamMember', 'teamMemberInputBody', teamMemberInputBody)
            const localVarPath = `/teams/{id}/members`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teamMemberInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Bulk Create Tasks
         * @param {BulkTaskCreateInputBody} bulkTaskCreateInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkCreateTasks: async (bulkTaskCreateInputBody: BulkTaskCreateInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkTaskCreateInputBody' is not null or undefined
            assertParamExists('bulkCreateTasks', 'bulkTaskCreateInputBody', bulkTaskCreateInputBody)
            const localVarPath = `/tasks/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkTaskCreateInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Bulk Delete Tasks
         * @param {BulkTaskDeleteInputBody} bulkTaskDeleteInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDeleteTasks: async (bulkTaskDeleteInputBody: BulkTaskDeleteInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkTaskDeleteInputBody' is not null or undefined
            assertParamExists('bulkDeleteTasks', 'bulkTaskDeleteInputBody', bulkTaskDeleteInputBody)
            const localVarPath = `/tasks/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkTaskDeleteInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Bulk Update Tasks Status
         * @param {BulkTaskUpdateInputBody} bulkTaskUpdateInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkUpdateTasksStatus: async (bulkTaskUpdateInputBody: BulkTaskUpdateInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkTaskUpdateInputBody' is not null or undefined
            assertParamExists('bulkUpdateTasksStatus', 'bulkTaskUpdateInputBody', bulkTaskUpdateInputBody)
            const localVarPath = `/tasks/bulk/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkTaskUpdateInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Project
         * @param {ProjectInputBody} projectInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProject: async (projectInputBody: ProjectInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectInputBody' is not null or undefined
            assertParamExists('createProject', 'projectInputBody', projectInputBody)
            const localVarPath = `/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(projectInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Task
         * @param {TaskInputBody} taskInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTask: async (taskInputBody: TaskInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskInputBody' is not null or undefined
            assertParamExists('createTask', 'taskInputBody', taskInputBody)
            const localVarPath = `/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(taskInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Team
         * @param {TeamInputBody} teamInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeam: async (teamInputBody: TeamInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teamInputBody' is not null or undefined
            assertParamExists('createTeam', 'teamInputBody', teamInputBody)
            const localVarPath = `/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teamInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Task
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTask: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTask', 'id', id)
            const localVarPath = `/tasks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Dashboard Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardStats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User Growth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserGrowth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/growth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User Badges
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBadges: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/badges`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjects: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTeams: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/teams`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User Login
         * @param {LoginInputBody} loginInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginInputBody: LoginInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginInputBody' is not null or undefined
            assertParamExists('login', 'loginInputBody', loginInputBody)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User Registration
         * @param {RegisterInputBody} registerInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register: async (registerInputBody: RegisterInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerInputBody' is not null or undefined
            assertParamExists('register', 'registerInputBody', registerInputBody)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Task Status
         * @param {string} id 
         * @param {TaskStatusUpdateInputBody} taskStatusUpdateInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaskStatus: async (id: string, taskStatusUpdateInputBody: TaskStatusUpdateInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTaskStatus', 'id', id)
            // verify required parameter 'taskStatusUpdateInputBody' is not null or undefined
            assertParamExists('updateTaskStatus', 'taskStatusUpdateInputBody', taskStatusUpdateInputBody)
            const localVarPath = `/tasks/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(taskStatusUpdateInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add Team Member
         * @param {string} id 
         * @param {TeamMemberInputBody} teamMemberInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTeamMember(id: string, teamMemberInputBody: TeamMemberInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTeamMember(id, teamMemberInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addTeamMember']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Bulk Create Tasks
         * @param {BulkTaskCreateInputBody} bulkTaskCreateInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkCreateTasks(bulkTaskCreateInputBody: BulkTaskCreateInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkCreateTasks(bulkTaskCreateInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.bulkCreateTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Bulk Delete Tasks
         * @param {BulkTaskDeleteInputBody} bulkTaskDeleteInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkDeleteTasks(bulkTaskDeleteInputBody: BulkTaskDeleteInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkDeleteTasks(bulkTaskDeleteInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.bulkDeleteTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Bulk Update Tasks Status
         * @param {BulkTaskUpdateInputBody} bulkTaskUpdateInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkUpdateTasksStatus(bulkTaskUpdateInputBody: BulkTaskUpdateInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkUpdateTasksStatus(bulkTaskUpdateInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.bulkUpdateTasksStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create Project
         * @param {ProjectInputBody} projectInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProject(projectInputBody: ProjectInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProject(projectInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create Task
         * @param {TaskInputBody} taskInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTask(taskInputBody: TaskInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTask(taskInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create Team
         * @param {TeamInputBody} teamInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTeam(teamInputBody: TeamInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTeam(teamInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createTeam']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Task
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTask(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTask(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Dashboard Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDashboardStats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDashboardStats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getDashboardStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User Growth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserGrowth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GrowthOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserGrowth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getUserGrowth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User Badges
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBadges(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BadgeListOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBadges(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listBadges']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listProjects(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectListOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listProjects(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listProjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskListOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTasks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTeams(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeamListOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTeams(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listTeams']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User Login
         * @param {LoginInputBody} loginInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginInputBody: LoginInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User Registration
         * @param {RegisterInputBody} registerInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async register(registerInputBody: RegisterInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.register(registerInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.register']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update Task Status
         * @param {string} id 
         * @param {TaskStatusUpdateInputBody} taskStatusUpdateInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTaskStatus(id: string, taskStatusUpdateInputBody: TaskStatusUpdateInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTaskStatus(id, taskStatusUpdateInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateTaskStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Add Team Member
         * @param {DefaultApiAddTeamMemberRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTeamMember(requestParameters: DefaultApiAddTeamMemberRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.addTeamMember(requestParameters.id, requestParameters.teamMemberInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Bulk Create Tasks
         * @param {DefaultApiBulkCreateTasksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkCreateTasks(requestParameters: DefaultApiBulkCreateTasksRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.bulkCreateTasks(requestParameters.bulkTaskCreateInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Bulk Delete Tasks
         * @param {DefaultApiBulkDeleteTasksRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDeleteTasks(requestParameters: DefaultApiBulkDeleteTasksRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.bulkDeleteTasks(requestParameters.bulkTaskDeleteInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Bulk Update Tasks Status
         * @param {DefaultApiBulkUpdateTasksStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkUpdateTasksStatus(requestParameters: DefaultApiBulkUpdateTasksStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.bulkUpdateTasksStatus(requestParameters.bulkTaskUpdateInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Project
         * @param {DefaultApiCreateProjectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProject(requestParameters: DefaultApiCreateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProjectOutputBody> {
            return localVarFp.createProject(requestParameters.projectInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Task
         * @param {DefaultApiCreateTaskRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTask(requestParameters: DefaultApiCreateTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskOutputBody> {
            return localVarFp.createTask(requestParameters.taskInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Team
         * @param {DefaultApiCreateTeamRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeam(requestParameters: DefaultApiCreateTeamRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createTeam(requestParameters.teamInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Task
         * @param {DefaultApiDeleteTaskRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTask(requestParameters: DefaultApiDeleteTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTask(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Dashboard Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardStats(options?: RawAxiosRequestConfig): AxiosPromise<DashboardOutputBody> {
            return localVarFp.getDashboardStats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User Growth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserGrowth(options?: RawAxiosRequestConfig): AxiosPromise<GrowthOutputBody> {
            return localVarFp.getUserGrowth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User Badges
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBadges(options?: RawAxiosRequestConfig): AxiosPromise<BadgeListOutputBody> {
            return localVarFp.listBadges(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjects(options?: RawAxiosRequestConfig): AxiosPromise<ProjectListOutputBody> {
            return localVarFp.listProjects(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Tasks
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTasks(options?: RawAxiosRequestConfig): AxiosPromise<TaskListOutputBody> {
            return localVarFp.listTasks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTeams(options?: RawAxiosRequestConfig): AxiosPromise<TeamListOutputBody> {
            return localVarFp.listTeams(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User Login
         * @param {DefaultApiLoginRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(requestParameters: DefaultApiLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginOutputBody> {
            return localVarFp.login(requestParameters.loginInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User Registration
         * @param {DefaultApiRegisterRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(requestParameters: DefaultApiRegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.register(requestParameters.registerInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Task Status
         * @param {DefaultApiUpdateTaskStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaskStatus(requestParameters: DefaultApiUpdateTaskStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<TaskOutputBody> {
            return localVarFp.updateTaskStatus(requestParameters.id, requestParameters.taskStatusUpdateInputBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addTeamMember operation in DefaultApi.
 */
export interface DefaultApiAddTeamMemberRequest {
    readonly id: string

    readonly teamMemberInputBody: TeamMemberInputBody
}

/**
 * Request parameters for bulkCreateTasks operation in DefaultApi.
 */
export interface DefaultApiBulkCreateTasksRequest {
    readonly bulkTaskCreateInputBody: BulkTaskCreateInputBody
}

/**
 * Request parameters for bulkDeleteTasks operation in DefaultApi.
 */
export interface DefaultApiBulkDeleteTasksRequest {
    readonly bulkTaskDeleteInputBody: BulkTaskDeleteInputBody
}

/**
 * Request parameters for bulkUpdateTasksStatus operation in DefaultApi.
 */
export interface DefaultApiBulkUpdateTasksStatusRequest {
    readonly bulkTaskUpdateInputBody: BulkTaskUpdateInputBody
}

/**
 * Request parameters for createProject operation in DefaultApi.
 */
export interface DefaultApiCreateProjectRequest {
    readonly projectInputBody: ProjectInputBody
}

/**
 * Request parameters for createTask operation in DefaultApi.
 */
export interface DefaultApiCreateTaskRequest {
    readonly taskInputBody: TaskInputBody
}

/**
 * Request parameters for createTeam operation in DefaultApi.
 */
export interface DefaultApiCreateTeamRequest {
    readonly teamInputBody: TeamInputBody
}

/**
 * Request parameters for deleteTask operation in DefaultApi.
 */
export interface DefaultApiDeleteTaskRequest {
    readonly id: string
}

/**
 * Request parameters for login operation in DefaultApi.
 */
export interface DefaultApiLoginRequest {
    readonly loginInputBody: LoginInputBody
}

/**
 * Request parameters for register operation in DefaultApi.
 */
export interface DefaultApiRegisterRequest {
    readonly registerInputBody: RegisterInputBody
}

/**
 * Request parameters for updateTaskStatus operation in DefaultApi.
 */
export interface DefaultApiUpdateTaskStatusRequest {
    readonly id: string

    readonly taskStatusUpdateInputBody: TaskStatusUpdateInputBody
}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Add Team Member
     * @param {DefaultApiAddTeamMemberRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addTeamMember(requestParameters: DefaultApiAddTeamMemberRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addTeamMember(requestParameters.id, requestParameters.teamMemberInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Bulk Create Tasks
     * @param {DefaultApiBulkCreateTasksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bulkCreateTasks(requestParameters: DefaultApiBulkCreateTasksRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).bulkCreateTasks(requestParameters.bulkTaskCreateInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Bulk Delete Tasks
     * @param {DefaultApiBulkDeleteTasksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bulkDeleteTasks(requestParameters: DefaultApiBulkDeleteTasksRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).bulkDeleteTasks(requestParameters.bulkTaskDeleteInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Bulk Update Tasks Status
     * @param {DefaultApiBulkUpdateTasksStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bulkUpdateTasksStatus(requestParameters: DefaultApiBulkUpdateTasksStatusRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).bulkUpdateTasksStatus(requestParameters.bulkTaskUpdateInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Project
     * @param {DefaultApiCreateProjectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createProject(requestParameters: DefaultApiCreateProjectRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createProject(requestParameters.projectInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Task
     * @param {DefaultApiCreateTaskRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTask(requestParameters: DefaultApiCreateTaskRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createTask(requestParameters.taskInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Team
     * @param {DefaultApiCreateTeamRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTeam(requestParameters: DefaultApiCreateTeamRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createTeam(requestParameters.teamInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Task
     * @param {DefaultApiDeleteTaskRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTask(requestParameters: DefaultApiDeleteTaskRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTask(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Dashboard Stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDashboardStats(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDashboardStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User Growth
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserGrowth(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUserGrowth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User Badges
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listBadges(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listBadges(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Projects
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listProjects(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listProjects(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Tasks
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTasks(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listTasks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Teams
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTeams(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listTeams(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User Login
     * @param {DefaultApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(requestParameters: DefaultApiLoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(requestParameters.loginInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User Registration
     * @param {DefaultApiRegisterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public register(requestParameters: DefaultApiRegisterRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).register(requestParameters.registerInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Task Status
     * @param {DefaultApiUpdateTaskStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTaskStatus(requestParameters: DefaultApiUpdateTaskStatusRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateTaskStatus(requestParameters.id, requestParameters.taskStatusUpdateInputBody, options).then((request) => request(this.axios, this.basePath));
    }
}



