// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActivityLog struct {
	ID        int64         `json:"id"`
	TenantID  uuid.UUID     `json:"tenant_id"`
	UserID    uuid.UUID     `json:"user_id"`
	TaskID    uuid.NullUUID `json:"task_id"`
	Action    string        `json:"action"`
	LoggedAt  sql.NullTime  `json:"logged_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Badge struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	IconSlug        string         `json:"icon_slug"`
	RequirementType string         `json:"requirement_type"`
}

type Notification struct {
	ID        uuid.UUID             `json:"id"`
	TenantID  uuid.UUID             `json:"tenant_id"`
	UserID    uuid.UUID             `json:"user_id"`
	Type      string                `json:"type"`
	Title     string                `json:"title"`
	Message   sql.NullString        `json:"message"`
	Data      pqtype.NullRawMessage `json:"data"`
	ReadAt    sql.NullTime          `json:"read_at"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProjectUser struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type Task struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullInt32  `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Team struct {
	ID        uuid.UUID    `json:"id"`
	TenantID  uuid.UUID    `json:"tenant_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type TeamMember struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

type Tenant struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Domain    string       `json:"domain"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsAdmin      bool           `json:"is_admin"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserBadge struct {
	UserID    uuid.UUID    `json:"user_id"`
	BadgeID   uuid.UUID    `json:"badge_id"`
	AwardedAt sql.NullTime `json:"awarded_at"`
}

type UserGrowth struct {
	UserID        uuid.UUID    `json:"user_id"`
	Level         int32        `json:"level"`
	Exp           int32        `json:"exp"`
	CharacterType string       `json:"character_type"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type UserStreak struct {
	UserID       uuid.UUID    `json:"user_id"`
	StreakType   string       `json:"streak_type"`
	CurrentCount int32        `json:"current_count"`
	MaxCount     int32        `json:"max_count"`
	LastDate     sql.NullTime `json:"last_date"`
}
