// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type ActivityLog struct {
	ID       int64         `json:"id"`
	TenantID uuid.UUID     `json:"tenant_id"`
	UserID   uuid.UUID     `json:"user_id"`
	TaskID   uuid.NullUUID `json:"task_id"`
	Action   string        `json:"action"`
	LoggedAt sql.NullTime  `json:"logged_at"`
}

type Badge struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	IconSlug        string         `json:"icon_slug"`
	RequirementType string         `json:"requirement_type"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProjectUser struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type Task struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullInt32  `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Team struct {
	ID        uuid.UUID    `json:"id"`
	TenantID  uuid.UUID    `json:"tenant_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type TeamMember struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

type Tenant struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Domain    string       `json:"domain"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserBadge struct {
	UserID    uuid.UUID    `json:"user_id"`
	BadgeID   uuid.UUID    `json:"badge_id"`
	AwardedAt sql.NullTime `json:"awarded_at"`
}

type UserGrowth struct {
	UserID        uuid.UUID    `json:"user_id"`
	Level         int32        `json:"level"`
	Exp           int32        `json:"exp"`
	CharacterType string       `json:"character_type"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}
