// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addExp = `-- name: AddExp :exec
UPDATE user_growth SET exp = exp + $2, updated_at = CURRENT_TIMESTAMP WHERE user_id = $1
`

type AddExpParams struct {
	UserID uuid.UUID `json:"user_id"`
	Exp    int32     `json:"exp"`
}

func (q *Queries) AddExp(ctx context.Context, arg AddExpParams) error {
	_, err := q.db.ExecContext(ctx, addExp, arg.UserID, arg.Exp)
	return err
}

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const assignProjectUser = `-- name: AssignProjectUser :exec
INSERT INTO project_users (project_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignProjectUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AssignProjectUser(ctx context.Context, arg AssignProjectUserParams) error {
	_, err := q.db.ExecContext(ctx, assignProjectUser, arg.ProjectID, arg.UserID)
	return err
}

const bulkDeleteTasks = `-- name: BulkDeleteTasks :exec
DELETE FROM tasks WHERE id = ANY($1::uuid[])
`

func (q *Queries) BulkDeleteTasks(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, bulkDeleteTasks, pq.Array(dollar_1))
	return err
}

const bulkUpdateTasksStatus = `-- name: BulkUpdateTasksStatus :exec
UPDATE tasks SET status = $2, updated_at = CURRENT_TIMESTAMP WHERE id = ANY($1::uuid[])
`

type BulkUpdateTasksStatusParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Status  string      `json:"status"`
}

func (q *Queries) BulkUpdateTasksStatus(ctx context.Context, arg BulkUpdateTasksStatusParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpdateTasksStatus, pq.Array(arg.Column1), arg.Status)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.TenantID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, project_id, assigned_to, title, description, status, priority, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullInt32  `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TenantID,
		arg.ProjectID,
		arg.AssignedTo,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (tenant_id, name) VALUES ($1, $2) RETURNING id, tenant_id, name, created_at, updated_at
`

type CreateTeamParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.TenantID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, password_hash, name, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserGrowth = `-- name: CreateUserGrowth :exec
INSERT INTO user_growth (user_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateUserGrowth(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createUserGrowth, userID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getDailyActivity = `-- name: GetDailyActivity :many
SELECT 
    logged_at::text as date,
    COUNT(*) FILTER (WHERE action = 'task_created') as created_count,
    COUNT(*) FILTER (WHERE action = 'task_completed') as completed_count
FROM activity_logs
WHERE user_id = $1 AND logged_at > CURRENT_DATE - INTERVAL '7 days'
GROUP BY logged_at
ORDER BY logged_at ASC
`

type GetDailyActivityRow struct {
	Date           string `json:"date"`
	CreatedCount   int64  `json:"created_count"`
	CompletedCount int64  `json:"completed_count"`
}

func (q *Queries) GetDailyActivity(ctx context.Context, userID uuid.UUID) ([]GetDailyActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyActivityRow
	for rows.Next() {
		var i GetDailyActivityRow
		if err := rows.Scan(&i.Date, &i.CreatedCount, &i.CompletedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    COUNT(*) as total_tasks,
    COUNT(*) FILTER (WHERE status != 'done') as pending_tasks,
    COUNT(*) FILTER (WHERE status = 'done') as completed_tasks
FROM tasks 
WHERE (assigned_to = $1 OR assigned_to IS NULL)
`

type GetDashboardStatsRow struct {
	TotalTasks     int64 `json:"total_tasks"`
	PendingTasks   int64 `json:"pending_tasks"`
	CompletedTasks int64 `json:"completed_tasks"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, assignedTo uuid.NullUUID) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats, assignedTo)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalTasks, &i.PendingTasks, &i.CompletedTasks)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, name, description, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT l.id, l.action, l.logged_at::text as date, COALESCE(t.title, 'Unknown Task')::text as task_title
FROM activity_logs l
LEFT JOIN tasks t ON l.task_id = t.id
WHERE l.user_id = $1
ORDER BY l.id DESC
LIMIT 10
`

type GetRecentActivityRow struct {
	ID        int64  `json:"id"`
	Action    string `json:"action"`
	Date      string `json:"date"`
	TaskTitle string `json:"task_title"`
}

func (q *Queries) GetRecentActivity(ctx context.Context, userID uuid.UUID) ([]GetRecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivityRow
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Date,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT id, name, domain, created_at, updated_at FROM tenants WHERE domain = $1
`

func (q *Queries) GetTenantByDomain(ctx context.Context, domain string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByDomain, domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, name, avatar_url, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGrowth = `-- name: GetUserGrowth :one
SELECT user_id, level, exp, character_type, updated_at FROM user_growth WHERE user_id = $1
`

func (q *Queries) GetUserGrowth(ctx context.Context, userID uuid.UUID) (UserGrowth, error) {
	row := q.db.QueryRowContext(ctx, getUserGrowth, userID)
	var i UserGrowth
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.Exp,
		&i.CharacterType,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, name, description, created_at, updated_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE project_id = COALESCE($1, project_id) ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context, projectID uuid.NullUUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.AssignedTo,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.name, u.avatar_url, u.created_at, u.updated_at
FROM users u
JOIN team_members tm ON u.id = tm.user_id
WHERE tm.team_id = $1
`

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, tenant_id, name, created_at, updated_at FROM teams ORDER BY created_at DESC
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBadges = `-- name: ListUserBadges :many
SELECT b.id, b.name, b.description, b.icon_slug, b.requirement_type
FROM badges b
JOIN user_badges ub ON b.id = ub.badge_id
WHERE ub.user_id = $1
`

func (q *Queries) ListUserBadges(ctx context.Context, userID uuid.UUID) ([]Badge, error) {
	rows, err := q.db.QueryContext(ctx, listUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Badge
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconSlug,
			&i.RequirementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const unassignProjectUser = `-- name: UnassignProjectUser :exec
DELETE FROM project_users WHERE project_id = $1 AND user_id = $2
`

type UnassignProjectUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) UnassignProjectUser(ctx context.Context, arg UnassignProjectUserParams) error {
	_, err := q.db.ExecContext(ctx, unassignProjectUser, arg.ProjectID, arg.UserID)
	return err
}

const updateLevel = `-- name: UpdateLevel :exec
UPDATE user_growth SET level = (exp / 100) + 1 WHERE user_id = $1
`

func (q *Queries) UpdateLevel(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLevel, userID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $2, description = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, tenant_id, name, description, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks 
SET title = $2, description = $3, status = $4, priority = $5, due_date = $6, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1 
RETURNING id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullInt32  `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
