// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addExp = `-- name: AddExp :exec
UPDATE user_growth SET exp = exp + $2, updated_at = CURRENT_TIMESTAMP WHERE user_id = $1
`

type AddExpParams struct {
	UserID uuid.UUID `json:"user_id"`
	Exp    int32     `json:"exp"`
}

func (q *Queries) AddExp(ctx context.Context, arg AddExpParams) error {
	_, err := q.db.ExecContext(ctx, addExp, arg.UserID, arg.Exp)
	return err
}

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const assignProjectUser = `-- name: AssignProjectUser :exec
INSERT INTO project_users (project_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignProjectUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AssignProjectUser(ctx context.Context, arg AssignProjectUserParams) error {
	_, err := q.db.ExecContext(ctx, assignProjectUser, arg.ProjectID, arg.UserID)
	return err
}

const awardBadge = `-- name: AwardBadge :exec
INSERT INTO user_badges (user_id, badge_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AwardBadgeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	BadgeID uuid.UUID `json:"badge_id"`
}

func (q *Queries) AwardBadge(ctx context.Context, arg AwardBadgeParams) error {
	_, err := q.db.ExecContext(ctx, awardBadge, arg.UserID, arg.BadgeID)
	return err
}

const bulkDeleteTasks = `-- name: BulkDeleteTasks :exec
UPDATE tasks SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = ANY($1::uuid[])
`

func (q *Queries) BulkDeleteTasks(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, bulkDeleteTasks, pq.Array(dollar_1))
	return err
}

const bulkUpdateTasksStatus = `-- name: BulkUpdateTasksStatus :exec
UPDATE tasks SET status = $2, updated_at = CURRENT_TIMESTAMP 
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

type BulkUpdateTasksStatusParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Status  string      `json:"status"`
}

func (q *Queries) BulkUpdateTasksStatus(ctx context.Context, arg BulkUpdateTasksStatusParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpdateTasksStatus, pq.Array(arg.Column1), arg.Status)
	return err
}

const countDistinctProjectsCompletedToday = `-- name: CountDistinctProjectsCompletedToday :one
SELECT COUNT(DISTINCT t.project_id)::int as count
FROM activity_logs al
JOIN tasks t ON al.task_id = t.id
WHERE al.user_id = $1 AND al.action = 'task_completed' AND al.logged_at = CURRENT_DATE
`

func (q *Queries) CountDistinctProjectsCompletedToday(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countDistinctProjectsCompletedToday, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countProjectsByUser = `-- name: CountProjectsByUser :one
SELECT COUNT(*)::int as count FROM project_users WHERE user_id = $1
`

func (q *Queries) CountProjectsByUser(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByUser, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTasksCompletedLastHour = `-- name: CountTasksCompletedLastHour :one
SELECT COUNT(*)::int as count FROM activity_logs
WHERE user_id = $1 AND action = 'task_completed' AND created_at >= NOW() - INTERVAL '1 hour'
`

func (q *Queries) CountTasksCompletedLastHour(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksCompletedLastHour, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTasksCompletedOnWeekends = `-- name: CountTasksCompletedOnWeekends :one
SELECT COUNT(*)::int as count FROM activity_logs
WHERE user_id = $1 AND action = 'task_completed' AND EXTRACT(DOW FROM logged_at) IN (0, 6)
`

func (q *Queries) CountTasksCompletedOnWeekends(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksCompletedOnWeekends, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTasksCompletedToday = `-- name: CountTasksCompletedToday :one
SELECT COUNT(*)::int as count FROM activity_logs
WHERE user_id = $1 AND action = 'task_completed' AND logged_at = CURRENT_DATE
`

func (q *Queries) CountTasksCompletedToday(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksCompletedToday, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTasksCompletedTodayInHour = `-- name: CountTasksCompletedTodayInHour :one
SELECT COUNT(*)::int as count FROM activity_logs
WHERE user_id = $1 AND action = 'task_completed' AND logged_at = CURRENT_DATE
  AND EXTRACT(HOUR FROM created_at)::int = $2::int
`

type CountTasksCompletedTodayInHourParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 int32     `json:"column_2"`
}

// Completions today within the given hour (server-local), e.g. 12 = 12:00-12:59.
func (q *Queries) CountTasksCompletedTodayInHour(ctx context.Context, arg CountTasksCompletedTodayInHourParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksCompletedTodayInHour, arg.UserID, arg.Column2)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTasksCreatedToday = `-- name: CountTasksCreatedToday :one
SELECT COUNT(*)::int as count FROM activity_logs
WHERE user_id = $1 AND action = 'task_created' AND logged_at = CURRENT_DATE
`

func (q *Queries) CountTasksCreatedToday(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTasksCreatedToday, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTeamMembershipsByUser = `-- name: CountTeamMembershipsByUser :one
SELECT COUNT(*)::int as count FROM team_members WHERE user_id = $1
`

func (q *Queries) CountTeamMembershipsByUser(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTeamMembershipsByUser, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::int as count FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec

INSERT INTO notifications (tenant_id, user_id, type, title, message, data)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateNotificationParams struct {
	TenantID uuid.UUID             `json:"tenant_id"`
	UserID   uuid.UUID             `json:"user_id"`
	Type     string                `json:"type"`
	Title    string                `json:"title"`
	Message  sql.NullString        `json:"message"`
	Data     pqtype.NullRawMessage `json:"data"`
}

// === Notification Queries ===
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Data,
	)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.TenantID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, project_id, assigned_to, title, description, status, priority, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, deleted_at, created_at, updated_at
`

type CreateTaskParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullInt32  `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TenantID,
		arg.ProjectID,
		arg.AssignedTo,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (tenant_id, name) VALUES ($1, $2) RETURNING id, tenant_id, name, created_at, updated_at
`

type CreateTeamParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.TenantID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, password_hash, name, avatar_url, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserGrowth = `-- name: CreateUserGrowth :exec
INSERT INTO user_growth (user_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateUserGrowth(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createUserGrowth, userID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getDailyActivity = `-- name: GetDailyActivity :many
SELECT 
    logged_at::text as date,
    COUNT(*) FILTER (WHERE action = 'task_created') as created_count,
    COUNT(*) FILTER (WHERE action = 'task_completed') as completed_count
FROM activity_logs
WHERE user_id = $1 AND logged_at > CURRENT_DATE - INTERVAL '7 days'
GROUP BY logged_at
ORDER BY logged_at ASC
`

type GetDailyActivityRow struct {
	Date           string `json:"date"`
	CreatedCount   int64  `json:"created_count"`
	CompletedCount int64  `json:"completed_count"`
}

func (q *Queries) GetDailyActivity(ctx context.Context, userID uuid.UUID) ([]GetDailyActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyActivityRow
	for rows.Next() {
		var i GetDailyActivityRow
		if err := rows.Scan(&i.Date, &i.CreatedCount, &i.CompletedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
    COUNT(*) as total_tasks,
    COUNT(*) FILTER (WHERE status != 'done') as pending_tasks,
    COUNT(*) FILTER (WHERE status = 'done') as completed_tasks
FROM tasks 
WHERE deleted_at IS NULL AND (assigned_to = $1 OR assigned_to IS NULL)
`

type GetDashboardStatsRow struct {
	TotalTasks     int64 `json:"total_tasks"`
	PendingTasks   int64 `json:"pending_tasks"`
	CompletedTasks int64 `json:"completed_tasks"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, assignedTo uuid.NullUUID) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats, assignedTo)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalTasks, &i.PendingTasks, &i.CompletedTasks)
	return i, err
}

const getLastActivityDate = `-- name: GetLastActivityDate :one
SELECT COALESCE(MAX(logged_at), '1970-01-01'::date)::date as last_date FROM activity_logs
WHERE user_id = $1 AND action = 'task_completed' AND logged_at < CURRENT_DATE
`

// Last completion date BEFORE today (activity logs are written before badge
// evaluation, so today's completion must be excluded for comeback detection).
func (q *Queries) GetLastActivityDate(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLastActivityDate, userID)
	var last_date time.Time
	err := row.Scan(&last_date)
	return last_date, err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, name, description, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTaskCounts = `-- name: GetProjectTaskCounts :one
SELECT COUNT(*)::int AS total, (COUNT(*) FILTER (WHERE status != 'done'))::int AS remaining
FROM tasks WHERE project_id = $1 AND deleted_at IS NULL
`

type GetProjectTaskCountsRow struct {
	Total     int32 `json:"total"`
	Remaining int32 `json:"remaining"`
}

func (q *Queries) GetProjectTaskCounts(ctx context.Context, projectID uuid.NullUUID) (GetProjectTaskCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectTaskCounts, projectID)
	var i GetProjectTaskCountsRow
	err := row.Scan(&i.Total, &i.Remaining)
	return i, err
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT l.id, l.action, l.logged_at::text as date, COALESCE(t.title, 'Unknown Task')::text as task_title
FROM activity_logs l
LEFT JOIN tasks t ON l.task_id = t.id
WHERE l.user_id = $1
ORDER BY l.id DESC
LIMIT 10
`

type GetRecentActivityRow struct {
	ID        int64  `json:"id"`
	Action    string `json:"action"`
	Date      string `json:"date"`
	TaskTitle string `json:"task_title"`
}

func (q *Queries) GetRecentActivity(ctx context.Context, userID uuid.UUID) ([]GetRecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivityRow
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Date,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreak = `-- name: GetStreak :one

SELECT user_id, streak_type, current_count, max_count, last_date FROM user_streaks WHERE user_id = $1 AND streak_type = $2
`

type GetStreakParams struct {
	UserID     uuid.UUID `json:"user_id"`
	StreakType string    `json:"streak_type"`
}

// === Streak Queries ===
func (q *Queries) GetStreak(ctx context.Context, arg GetStreakParams) (UserStreak, error) {
	row := q.db.QueryRowContext(ctx, getStreak, arg.UserID, arg.StreakType)
	var i UserStreak
	err := row.Scan(
		&i.UserID,
		&i.StreakType,
		&i.CurrentCount,
		&i.MaxCount,
		&i.LastDate,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, deleted_at, created_at, updated_at FROM tasks WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one

SELECT id, tenant_id, name, created_at, updated_at FROM teams WHERE id = $1
`

// === Team Extra Queries ===
func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMemberRole = `-- name: GetTeamMemberRole :one
SELECT role FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetTeamMemberRoleParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMemberRole(ctx context.Context, arg GetTeamMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTeamMemberRole, arg.TeamID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT id, name, domain, created_at, updated_at FROM tenants WHERE domain = $1
`

func (q *Queries) GetTenantByDomain(ctx context.Context, domain string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByDomain, domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, name, avatar_url, is_admin, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, name, avatar_url, is_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGrowth = `-- name: GetUserGrowth :one
SELECT user_id, level, exp, character_type, updated_at FROM user_growth WHERE user_id = $1
`

func (q *Queries) GetUserGrowth(ctx context.Context, userID uuid.UUID) (UserGrowth, error) {
	row := q.db.QueryRowContext(ctx, getUserGrowth, userID)
	var i UserGrowth
	err := row.Scan(
		&i.UserID,
		&i.Level,
		&i.Exp,
		&i.CharacterType,
		&i.UpdatedAt,
	)
	return i, err
}

const insertActivityLog = `-- name: InsertActivityLog :exec

INSERT INTO activity_logs (tenant_id, user_id, task_id, action)
VALUES ($1, $2, $3, $4)
`

type InsertActivityLogParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	UserID   uuid.UUID     `json:"user_id"`
	TaskID   uuid.NullUUID `json:"task_id"`
	Action   string        `json:"action"`
}

// === Activity Log Queries ===
func (q *Queries) InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, insertActivityLog,
		arg.TenantID,
		arg.UserID,
		arg.TaskID,
		arg.Action,
	)
	return err
}

const listAllBadges = `-- name: ListAllBadges :many
SELECT id, name, description, icon_slug, requirement_type FROM badges
`

func (q *Queries) ListAllBadges(ctx context.Context) ([]Badge, error) {
	rows, err := q.db.QueryContext(ctx, listAllBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Badge
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconSlug,
			&i.RequirementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, user_id, type, title, message, data, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.name, u.avatar_url, u.is_admin, u.created_at, u.updated_at
FROM users u
JOIN project_users pu ON u.id = pu.user_id
WHERE pu.project_id = $1
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.AvatarUrl,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, tenant_id, name, description, created_at, updated_at FROM projects 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, deleted_at, created_at, updated_at FROM tasks
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR project_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::int IS NULL OR priority = $3)
  AND ($4::timestamptz IS NULL OR due_date >= $4)
  AND ($5::timestamptz IS NULL OR due_date <= $5)
ORDER BY created_at DESC
LIMIT $7 OFFSET $6
`

type ListTasksParams struct {
	ProjectID   uuid.NullUUID  `json:"project_id"`
	Status      sql.NullString `json:"status"`
	Priority    sql.NullInt32  `json:"priority"`
	DueDateFrom sql.NullTime   `json:"due_date_from"`
	DueDateTo   sql.NullTime   `json:"due_date_to"`
	Offset      int32          `json:"offset"`
	Limit       int32          `json:"limit"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.ProjectID,
		arg.Status,
		arg.Priority,
		arg.DueDateFrom,
		arg.DueDateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.AssignedTo,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id, u.email, u.name, u.avatar_url, tm.role
FROM users u
JOIN team_members tm ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY CASE tm.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, u.name ASC
`

type ListTeamMembersRow struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Role      string         `json:"role"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, tenant_id, name, created_at, updated_at FROM teams 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTeamsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, tenant_id, user_id, type, title, message, data, read_at, created_at FROM notifications
WHERE user_id = $1 AND read_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListUnreadNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBadges = `-- name: ListUserBadges :many
SELECT b.id, b.name, b.description, b.icon_slug, b.requirement_type
FROM badges b
JOIN user_badges ub ON b.id = ub.badge_id
WHERE ub.user_id = $1
`

func (q *Queries) ListUserBadges(ctx context.Context, userID uuid.UUID) ([]Badge, error) {
	rows, err := q.db.QueryContext(ctx, listUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Badge
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconSlug,
			&i.RequirementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const removeBadge = `-- name: RemoveBadge :exec
DELETE FROM user_badges WHERE user_id = $1 AND badge_id = $2
`

type RemoveBadgeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	BadgeID uuid.UUID `json:"badge_id"`
}

func (q *Queries) RemoveBadge(ctx context.Context, arg RemoveBadgeParams) error {
	_, err := q.db.ExecContext(ctx, removeBadge, arg.UserID, arg.BadgeID)
	return err
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, tenant_id, email, password_hash, name, avatar_url, is_admin, created_at, updated_at FROM users 
WHERE (email ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.AvatarUrl,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subtractExp = `-- name: SubtractExp :exec

UPDATE user_growth SET exp = GREATEST(exp - $2, 0), updated_at = CURRENT_TIMESTAMP WHERE user_id = $1
`

type SubtractExpParams struct {
	UserID uuid.UUID `json:"user_id"`
	Exp    int32     `json:"exp"`
}

// === Gamification Extra Queries ===
func (q *Queries) SubtractExp(ctx context.Context, arg SubtractExpParams) error {
	_, err := q.db.ExecContext(ctx, subtractExp, arg.UserID, arg.Exp)
	return err
}

const unassignProjectUser = `-- name: UnassignProjectUser :exec
DELETE FROM project_users WHERE project_id = $1 AND user_id = $2
`

type UnassignProjectUserParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) UnassignProjectUser(ctx context.Context, arg UnassignProjectUserParams) error {
	_, err := q.db.ExecContext(ctx, unassignProjectUser, arg.ProjectID, arg.UserID)
	return err
}

const updateCharacterType = `-- name: UpdateCharacterType :exec
UPDATE user_growth SET character_type = $2, updated_at = CURRENT_TIMESTAMP WHERE user_id = $1
`

type UpdateCharacterTypeParams struct {
	UserID        uuid.UUID `json:"user_id"`
	CharacterType string    `json:"character_type"`
}

func (q *Queries) UpdateCharacterType(ctx context.Context, arg UpdateCharacterTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterType, arg.UserID, arg.CharacterType)
	return err
}

const updateLevel = `-- name: UpdateLevel :exec
UPDATE user_growth SET level = (exp / 100) + 1 WHERE user_id = $1
`

func (q *Queries) UpdateLevel(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLevel, userID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec

UPDATE users SET password_hash = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

// === Auth Extra Queries ===
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $2, description = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, tenant_id, name, description, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, description = $3, status = $4, priority = $5, due_date = $6, assigned_to = $7, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, deleted_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullInt32  `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.AssignedTo,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $2, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, project_id, assigned_to, title, description, status, priority, due_date, deleted_at, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET name = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, tenant_id, name, created_at, updated_at
`

type UpdateTeamParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, updateTeam, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, avatar_url = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, tenant_id, email, password_hash, name, avatar_url, is_admin, created_at, updated_at
`

type UpdateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStreak = `-- name: UpsertStreak :exec
INSERT INTO user_streaks (user_id, streak_type, current_count, max_count, last_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, streak_type) DO UPDATE SET
    current_count = EXCLUDED.current_count,
    max_count = GREATEST(user_streaks.max_count, EXCLUDED.max_count),
    last_date = EXCLUDED.last_date
`

type UpsertStreakParams struct {
	UserID       uuid.UUID    `json:"user_id"`
	StreakType   string       `json:"streak_type"`
	CurrentCount int32        `json:"current_count"`
	MaxCount     int32        `json:"max_count"`
	LastDate     sql.NullTime `json:"last_date"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) error {
	_, err := q.db.ExecContext(ctx, upsertStreak,
		arg.UserID,
		arg.StreakType,
		arg.CurrentCount,
		arg.MaxCount,
		arg.LastDate,
	)
	return err
}
